# Generated by Django 3.2.7 on 2021-09-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='required_ingredients',
        ),
        migrations.AlterField(
            model_name='drinkingredients',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_ingredients', to='bartender_app.drink'),
        ),
    ]
