# Generated by Django 3.2.7 on 2021-09-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0003_auto_20210914_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='required_ingredients',
        ),
        migrations.AddField(
            model_name='drink',
            name='required_ingredients',
            field=models.ManyToManyField(null=True, to='bartender_app.DrinkIngredient'),
        ),
        migrations.AlterField(
            model_name='drinkingredient',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='bartender_app.ingredient'),
        ),
    ]
