# Generated by Django 3.2.7 on 2021-09-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0004_auto_20210914_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredient',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='drinkingredient',
            name='measurement',
            field=models.CharField(default='ml', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('spirit', 'SPIRIT'), ('mixer', 'MIXER'), ('garnish', 'GARNISH')], default='mixer', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='media/drinks'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='required_ingredients',
            field=models.ManyToManyField(to='bartender_app.DrinkIngredient'),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_ingredients', to='bartender_app.user'),
        ),
    ]
