# Generated by Django 3.2.7 on 2021-09-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0005_auto_20210918_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='required_ingredients',
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='bartender_app.drinkingredient'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='instructions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='bartender_app.drinkinstruction'),
        ),
    ]
