# Generated by Django 3.2.7 on 2021-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0007_auto_20210918_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingredient',
            name='quantity_needed',
            field=models.FloatField(default=0),
        ),
    ]
