# Generated by Django 3.2.7 on 2021-09-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0009_alter_drinkingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingredient',
            name='measurement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
