# Generated by Django 3.2.7 on 2021-09-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender_app', '0010_alter_drinkingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_drinks', to='bartender_app.ingredient'),
        ),
    ]
