# Generated by Django 3.2.7 on 2021-10-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bartender_app', '0011_alter_drinkingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_ingredients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
