# Generated by Django 4.0 on 2021-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartender_app", "0014_migrate_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
