# Generated by Django 4.0 on 2021-12-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartender_app", "0015_ingredient_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DrinkInstruction",
        ),
    ]
