# Generated by Django 4.0.1 on 2022-07-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bartender_app", "0018_category_drink_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="media/glasses")),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="drink",
            name="method",
            field=models.TextField(
                choices=[("shaken", "Shaken"), ("stirred", "Stirred")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drink",
            name="glass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bartender_app.glass",
            ),
        ),
    ]
